# Generated by Django 4.2 on 2023-04-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_fertilizer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='type',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='watering',
            name='water',
            field=models.BooleanField(default=True),
        ),
    ]
