# Generated by Django 4.2 on 2023-07-12 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_fertilizer_type_alter_watering_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GrowingEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('water_requirements', models.CharField(max_length=255)),
                ('sun_exposure', models.CharField(blank=True, choices=[('full_sun', 'Full Sun'), ('partial_sun', 'Partial Sun'), ('partial_shade', 'Partial Shade'), ('full_shade', 'Full Shade')], max_length=255, null=True)),
                ('temperature_range', models.CharField(blank=True, max_length=255, null=True)),
                ('light_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('garden_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(blank=True, max_length=255, null=True)),
                ('yield_production', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.growingenvironment')),
            ],
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='fertilizers',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='nitrogen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='organic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='companion_plants',
            field=models.ManyToManyField(blank=True, to='main_app.plant'),
        ),
        migrations.AddField(
            model_name='plant',
            name='diseases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='edible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='life_cycle',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('perennial', 'Perennial'), ('biennial', 'Biennial')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='pests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_x_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_x_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_y_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='spacing_y_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='variety',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_requirements',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('fruit', 'Fruit'), ('herb', 'Herb'), ('flower', 'Flower')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Watering',
        ),
        migrations.AddField(
            model_name='userplant',
            name='fertilizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.fertilizer'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='main_app.garden'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant'),
        ),
        migrations.AddField(
            model_name='userplant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
        migrations.AddField(
            model_name='garden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user'),
        ),
    ]
